runtime: python311

entrypoint: gunicorn -b :$PORT main:app

instance_class: F2

automatic_scaling:
  max_instances: 3

env_variables:
  APP_URL: "https://f1-cloud-lvtl.nw.r.appspot.com/"
  GOOGLE_APPLICATION_CREDENTIALS: "f1-cloud-lvtl-firebase-adminsdk-fbsvc-978b212e8f.json"
  GAE_USE_CUSTOM_STAGING_BUCKET: "true"
handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
